### PR TITLE
Disabling specific days in date picker

### PR DESCRIPTION
**Pull request by wojta**
I needed the way to disallow and disable some dates from selection.
So now you can do for example:
```
datepicker(allowedDateValidator = {
            it.dayOfWeek !== DayOfWeek.SATURDAY && it.dayOfWeek !== DayOfWeek.SUNDAY
        }) 
```

### CODE REVIEW

**Comment by vanpra** [comment]
Thanks for the contribution. It looks like you have a wildcard import in one of the files. You can check the linting locally by running  `./gradlew spotlessCheck`

**Comment by wojta** [comment]
I don't know how to generate the screenshot for the test I added and how to fix that Codacy. I think that the name of the variable `allowedDatesValidator` follows that regexp.

**Comment by wojta** [comment]
@vanpra please advise, thanks

**Comment by vanpra** [comment]
I will be adding a contribution guide in the next couple of days which will give a run through the right settings for the emulator and how to capture capture screenshots for new tests.

**Comment by vanpra** [comment]
I've added a contribution guide with the details about how to run the screenshot tests and update them. Let me know if you still have any questions

**Comment by wojta** [comment]
@vanpra Do you think that you can make a new release, so we can link to the library and not to deploy our own maven package?Thanks.

**Pull request merged**
