### PR TITLE
min, max for datepicker

### PR DESCRIPTION
**Pull request by msomu**
Ability to pass date range for DatePicker.

Have changed the yearRange to dateRange : ClosedRange<LocalDate>

### CODE REVIEW

**Comment by vanpra** [comment]
Thanks a lot for the contribution. I've tested it out and it seems like if the initial date is outside the range it still selects it, so could you add something to coerce the `initalDate` into the range.

**Comment by msomu** [comment]
I have made dateRange to be calculated from the initial date with +75 and -75 years from it, this can change if needed. If both initial date, dateRange are specified and if the initial date is not in the given dateRange it will throw an error both at the datePicker and at the dateTimePicker.

**Comment by vanpra** [comment]
Thanks, that sounds good. I'll test it out again and take a look at the code later today.

**Comment by vanpra** [comment]
There were a few remember statements in a few places so I added those in but it still seems like the extra range processing causes the date picker to lag a lot. I think that this is more down to the implementation of the date picker itself rather than the additions of this commit so I'll make a few performance improvements to it in a separate branch and merge this in after that is done.

**Comment by vanpra** [comment]
So I've done more testing and optimisation but it still looks like the date picker is too UI intensive. It seems like most of this is due to the calendar view but I need to do some more profiling in order to narrow down the exact location. I'll try and get this done asap but I'm pretty busy at the moment so it might still be a while till I can get around to it.

**Comment by tommyzat** [comment]
Hello! I really appreciate the library. Is an ETA available? I'm craving this feature. Thanks!

**Comment by jakhongir-mx51** [comment]
This PR has a bug when selectableDateRange's start date is not in the same month as the end date.

**Pull request closed without merging**
